In [52]:
%matplotlib inline
import pandas as pd

In [53]:
'''from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))'''

"from IPython.core.display import HTML\ncss = open('style-table.css').read() + open('style-notebook.css').read()\nHTML('<style>{}</style>'.format(css))"

In [54]:
titles = pd.DataFrame.from_csv('data/titles.csv', index_col=None)
titles.tail()

                        title  year
216531  Nobody Waved Good-bye  1964
216532                  E yue  2005
216533           Lakota Girls  2015
216534         Kroniki domowe  1997
216535           The Sting II  1983

In [55]:
cast = pd.DataFrame.from_csv('data/cast.csv', index_col=None)
cast.head()

                               title  year       name   type character   n
0                    Suuri illusioni  1985     Homo $  actor    Guests  22
1     Gangsta Rap: The Glockumentary  2007  Too $hort  actor   Himself NaN
2                  Menace II Society  1993  Too $hort  actor   Lew-Loc  27
3  Porndogs: The Adventures of Sadie  2009  Too $hort  actor     Bosco   3
4                 Stop Pepper Palmer  2014  Too $hort  actor   Himself NaN

### How many movies are listed in the titles dataframe?

In [56]:
len(titles)

216536

### What are the earliest two films listed in the titles dataframe?

In [57]:
titles.sort_values('year').head(2)

                                                    title  year
165628                                         Miss Jerry  1894
85967   Reproduction of the Corbett and Fitzsimmons Fight  1897

### How many movies have the title "Hamlet"?

In [58]:
hamlets = titles[titles.title == 'Hamlet']
hamlets

         title  year
5572    Hamlet  1948
26218   Hamlet  2016
37483   Hamlet  2015
42348   Hamlet  1990
43621   Hamlet  1910
68452   Hamlet  1954
86001   Hamlet  1976
88032   Hamlet  1987
88225   Hamlet  2000
91989   Hamlet  1921
114512  Hamlet  1969
155033  Hamlet  1913
164076  Hamlet  2009
170470  Hamlet  1964
187517  Hamlet  1996
193332  Hamlet  2011
195542  Hamlet  1911
206385  Hamlet  1973
208347  Hamlet  2014

In [59]:
len(hamlets)

19

### How many movies are titled "North by Northwest"?

In [60]:
nnw = titles[titles.title == "North by Northwest"]
nnw

                     title  year
129864  North by Northwest  1959

In [61]:
len(nnw)

1

### When was the first movie titled "Hamlet" made?

In [62]:
hamlets.sort_values('year')

         title  year
43621   Hamlet  1910
195542  Hamlet  1911
155033  Hamlet  1913
91989   Hamlet  1921
5572    Hamlet  1948
68452   Hamlet  1954
170470  Hamlet  1964
114512  Hamlet  1969
206385  Hamlet  1973
86001   Hamlet  1976
88032   Hamlet  1987
42348   Hamlet  1990
187517  Hamlet  1996
88225   Hamlet  2000
164076  Hamlet  2009
193332  Hamlet  2011
208347  Hamlet  2014
37483   Hamlet  2015
26218   Hamlet  2016

In [63]:
hamlets.sort_values('year').head(1)

        title  year
43621  Hamlet  1910

### List all of the "Treasure Island" movies from earliest to most recent.

In [64]:
titles[titles.title == "Treasure Island"].sort_values('year')

                  title  year
191892  Treasure Island  1918
47866   Treasure Island  1920
193429  Treasure Island  1934
90437   Treasure Island  1950
213589  Treasure Island  1972
103921  Treasure Island  1973
191299  Treasure Island  1985
167148  Treasure Island  1999

### How many movies were made in the year 1950?

In [65]:
len(titles[titles.year == 1950])

1038

In [66]:
titles[titles.year == 1950]

                                                    title  year
89                                       Botta e risposta  1950
520                                   Un certain monsieur  1950
953                                     Vom Teufel gejagt  1950
1052                                          The Jackpot  1950
1237                                 This Side of the Law  1950
1329                                            The Actor  1950
1466                                  Tanssi yli hautojen  1950
1574                                 Akatsuki no tsuiseki  1950
1623                                Atom Man vs. Superman  1950
1736                                 The Sun Sets at Dawn  1950
1823                                    Paolo e Francesca  1950
2096                                   Annie Get Your Gun  1950
2451                                     O Pecado de Nina  1950
2650                                   Hit Parade of 1951  1950
2997                                  Belle of Old Mexico  1950
3116                                              Senritu  1950
3131                                    Gunmen of Abilene  1950
3197                                       Garota Mineira  1950
3199                                    Nancy Goes to Rio  1950
3233                                         Texas Dynamo  1950
3304                                         I fuorilegge  1950
3325                                            Ogni Baku  1950
3472                                     La Marie du port  1950
3584                                       Lyn-fotografen  1950
3885                               Kein Engel ist so rein  1950
4026                                   Comanche Territory  1950
4115                                   Mujeres en mi vida  1950
4225                                 Wenn eine Frau liebt  1950
4481                                    The Sleeping City  1950
4913                                           Ma no ogon  1950
...                                                   ...   ...
209827                                        The Nevadan  1950
209892  Kike wadatsumi no koe: Nippon senbotsu gakusei...  1950
210310                                   Southside 1-1000  1950
210380                                        Eden no umi  1950
210387                                         Sasameyuki  1950
210421                                           Le furet  1950
210647                            Code of the Silver Sage  1950
210725                           La danseuse de Marrakech  1950
211149                               The Astonished Heart  1950
211182                            Desperadoes of the West  1950
211307                            Il figlio di d'Artagnan  1950
211670                                 Shadow of the Past  1950
211679                                    The White Tower  1950
211900                              Il sentiero dell'odio  1950
211978                                       Cage of Gold  1950
212116                                     Verlobte Leute  1950
212566                                        Timber Fury  1950
212595                              The Invisible Monster  1950
212620                             Federal Agent at Large  1950
213011                               Matrimonio y mortaja  1950
213298                                         Gadano Bel  1950
213628                                      Captain China  1950
214014                                    Fake's Progress  1950
214256                                            Sangram  1950
214536                    Sazae-san: Nodojiman uta-gassen  1950
214799                                    Key to the City  1950
215524                                       Dwie brygady  1950
215607                                 La negra Angustias  1950
215662                                              Jogan  1950
216173                                       Rasuna valea  1950

[1038 rows x 2 columns]

### How many movies were made in the year 1960?

In [67]:
titles[titles.year == 1960]

                                  title  year
104                     Cone of Silence  1960
239                     Magavari Mayalu  1960
314                       The Challenge  1960
429             Dos hijos desobedientes  1960
432                            Nianchan  1960
817                    Pretty Boy Floyd  1960
844                   Caught in the Net  1960
951                 Un militare e mezzo  1960
1181                           Fortunat  1960
1277                        Cheoljomang  1960
1631                 Un dollaro di fifa  1960
1639                   Pote tin Kyriaki  1960
1714                   Scent of Mystery  1960
2026                    Jiao feng ye yu  1960
2075                         Isi neraka  1960
2084                Outside the Kulambo  1960
2146                 Le bal des espions  1960
2200                      Ku hai gu chu  1960
2322                    Doon Pa sa Amin  1960
2340    Khrustalnyy bashmachok Zolushki  1960
2419                    Ji ming gou dao  1960
2441                 Cheonchun ilbeonji  1960
2525                       Unos sa laot  1960
2713                            Gambler  1960
2772                    Operation Cupid  1960
2964                       Telli kursun  1960
3092              Tatlong patak ng luha  1960
3279                 Home from the Hill  1960
3307                           Jie tong  1960
3582                      Vivo o muerto  1960
...                                 ...   ...
211200                The Mountain Road  1960
211333                          Pakipot  1960
211480   Kenju burai-cho: Asunaki otoko  1960
211800            La strada dei giganti  1960
211935                 Ski Troop Attack  1960
212503                       Kuang lian  1960
212783                            India  1960
213034                  Walang Pangalan  1960
213233                Secretul cifrului  1960
213406       Baltiyskoe nebo - 2 seriya  1960
213410    The Secret of the Purple Reef  1960
213585                Bells Are Ringing  1960
213862             L'affaire d'une nuit  1960
213904               Kankkulan kaivolla  1960
214128                     Dobol trobol  1960
214268                   Xue feng mo nu  1960
214301                 Ipagdarasal kita  1960
214448                 Avaghachi Sansar  1960
214691            Nakausap Ko ang Diyos  1960
214706                           Manzil  1960
214916                         El crack  1960
214957                          Domaren  1960
215023                To agori p' agapo  1960
215106          Les vieux de la vieille  1960
215283                        Heldinnen  1960
215321                  Me importa poco  1960
215370            Tres angelitos negros  1960
215857           Roop Matti Baz Bahadur  1960
215906                        Wu cai lu  1960
216124                      Fuefukigawa  1960

[1473 rows x 2 columns]

In [68]:
len(titles[titles.year == 1960])

1473

### How many movies were made from 1950 through 1959?

In [69]:
fifties = titles[(titles.year >= 1950) & (titles.year <= 1959)]
fifties

                                         title  year
8                               Women's Prison  1955
40      La momia azteca contra el robot humano  1958
45                                 Mavi boncuk  1958
62                     Radar Men from the Moon  1952
89                            Botta e risposta  1950
91                         Perdeu-se um Marido  1957
111                             Qiu yu can hua  1953
113                                 Hi no tori  1956
127                            Rock Rock Rock!  1956
130                           Quem Sabe, Sabe!  1956
162                            Yin shen nu xia  1957
202                            Next to No Time  1958
242                           Pardon My French  1951
255                         Pelli Chesi Choodu  1952
304                                    Ukikusa  1959
400                      Prisionera del pasado  1954
446                      The Lost Class of '59  1959
461                             Dorogoy tsenoy  1957
465                           Ice Cold in Alex  1958
467                                    Leonora  1951
504                               Gli sbandati  1955
520                        Un certain monsieur  1950
521                        Doctor in the House  1954
530                             Let's Go Navy!  1951
542                          Mamma sconosciuta  1956
543                                Baba Wansui  1954
546                                 Chor Bazar  1954
549                   Kung ako'y maging dalaga  1954
606                                   Massacre  1956
608                                 Jacqueline  1959
...                                        ...   ...
216013                        Die blaue Stunde  1953
216014                      Babaeng hampaslupa  1952
216029                        La dulce enemiga  1957
216067                            Blowing Wild  1953
216068                     She Couldn't Say No  1954
216075                  The Pride of St. Louis  1952
216089                          Ying du yan ji  1955
216162                     Tre storie proibite  1952
216168                 Vater sein dagegen sehr  1957
216173                            Rasuna valea  1950
216175                            Cara de Goma  1959
216198                             At Gunpoint  1955
216205                                La sfida  1958
216218                          Flesh and Fury  1952
216219                        Tuloy ang ligaya  1958
216239                         Fu chang fu sui  1957
216245                   Das Bad auf der Tenne  1956
216248           Ggotdo saengmyeongi iddamyeon  1958
216267                      Bandits of Corsica  1953
216275                              Pipa xiang  1953
216278                                    Dino  1957
216309                       Project Moon Base  1953
216332                         O Grande Pintor  1955
216338                     The Fighting Chance  1955
216341                     Himmel och pannkaka  1959
216360           To mystiko tis katigoroumenis  1958
216408                    Tischlein, deck dich  1956
216442                        Some Like It Hot  1959
216467                             Black Widow  1951
216501                       Te sigo esperando  1952

[12175 rows x 2 columns]

In [70]:
len(fifties)

12175

### In what years has a movie titled "Batman" been released?

In [71]:
titles[titles.title == "Batman"].year

52270    1989
69682    1943
Name: year, dtype: int64

### How many roles were there in the movie "Inception"?

In [72]:
cast = pd.DataFrame.from_csv('data/cast.csv', index_col=None)
cast.head()

                               title  year       name   type character   n
0                    Suuri illusioni  1985     Homo $  actor    Guests  22
1     Gangsta Rap: The Glockumentary  2007  Too $hort  actor   Himself NaN
2                  Menace II Society  1993  Too $hort  actor   Lew-Loc  27
3  Porndogs: The Adventures of Sadie  2009  Too $hort  actor     Bosco   3
4                 Stop Pepper Palmer  2014  Too $hort  actor   Himself NaN

In [73]:
len(cast[cast.title == "Inception"])

75

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [74]:
len(cast[(cast.title == "Inception") & cast.n.isnull()])

24

In [75]:
cast[(cast.title == "Inception") & cast.n.isnull()]

,title,year,name,type,character,n
87509,Inception,2010,Michael (III) August,actor,LAX Passenger,NaN
177529,Inception,2010,Ken Bhan,actor,Mombasan Gambler,NaN
338650,Inception,2010,John Ceallach,actor,LAX Passenger,NaN
620017,Inception,2010,Seve Esposito,actor,Italian Gambler,NaN
641396,Inception,2010,Zachary Christopher Fay,actor,Extra,NaN
758206,Inception,2010,Daniel Girondeaud,actor,Bridge Sub Con,NaN
913778,Inception,2010,Andrew Hoagland,actor,Pedestrian,NaN
994430,Inception,2010,Charles Jarrell,actor,Hotel Guest,NaN
1006517,Inception,2010,Seong-hwan Jo,actor,Japanese Landing Crew,NaN
1016854,Inception,2010,Alonzo F. Jones,actor,Mombasan Casino Staff,NaN
1078707,Inception,2010,Mobin Khan,actor,Mombasa Casino Cashier,NaN
1131343,Inception,2010,Shunsaku Kud?,actor,Saito's Bodyguard Officer,NaN
1174627,Inception,2010,John (IX) Lawson,actor,Street Person,NaN
1189210,Inception,2010,Jean-Christophe Leger,actor,French Student,NaN
1510792,Inception,2010,Fran?ois-Marie Nivon,actor,A Passer-By,NaN
1664848,Inception,2010,Scott Pretty,actor,Pedestrian,NaN
1741223,Inception,2010,Benjamin (II) Riley,actor,Bridge Sub Con,NaN
1812307,Inception,2010,Norman Saleet,actor,Airport Patron,NaN
1926903,Inception,2010,Colin (XXV) Smith,actor,Airport Patron,NaN
2027066,Inception,2010,Affan Tareen,actor,Denison,NaN
2523780,Inception,2010,Youlanda Davis,actress,Mombasan Cashier,NaN
2659203,Inception,2010,Natalie Goldwin,actress,LAX Passenger,NaN
2750551,Inception,2010,Marguerite Insolia,actress,Reporter,NaN
2922727,Inception,2010,Leticia (III) Martinez,actress,Airport Patron,NaN

### But how many roles in the movie "Inception" did receive an "n" value?

In [76]:
inceptioners = cast[(cast.title == "Inception") & (cast.n.notnull())]
inceptioners

,title,year,name,type,character,n
133222,Inception,2010,Peter Basham,actor,Fischer's Jet Captain,44
164939,Inception,2010,Tom Berenger,actor,Browning,8
233897,Inception,2010,Virgile Bramly,actor,Bridge Sub Con,29
294940,Inception,2010,Michael Caine,actor,Miles,11
301065,Inception,2010,Earl Cameron,actor,Elderly Bald Man,20
391751,Inception,2010,Nicolas Clerc,actor,Bridge Sub Con,26
401470,Inception,2010,Adam (IV) Cole,actor,Bar Sub Con,34
468468,Inception,2010,Jean-Michel Dagory,actor,Bridge Sub Con,30
535035,Inception,2010,Leonardo DiCaprio,actor,Cobb,1
642982,Inception,2010,Russ Fega,actor,Cab Driver,23
668500,Inception,2010,Mark Fleischmann,actor,Penrose Sub Con,32
732633,Inception,2010,Michael Gaston,actor,Immigration Officer,45
736493,Inception,2010,Johnathan Geare,actor,James (3 years),17
754335,Inception,2010,Carl Gilliard,actor,Lobby Sub Con,40
755544,Inception,2010,Jack Gilroy,actor,Old Cobb,50
779602,Inception,2010,Joseph Gordon-Levitt,actor,Arthur,2
825595,Inception,2010,Lukas Haas,actor,Nash,12
853332,Inception,2010,Tom Hardy,actor,Eames,4
877566,Inception,2010,Ryan Hayward,actor,Lawyer,21
1061978,Inception,2010,Tim Kelleher,actor,Thin Man,24
1186951,Inception,2010,Tai-Li Lee,actor,Tadashi,13
1319385,Inception,2010,Tohoru Masamune,actor,Japanese Security Guard,18
1465850,Inception,2010,Cillian Murphy,actor,Robert Fischer,7
1468483,Inception,2010,Jack (III) Murray,actor,Bar Sub Con,35
1513369,Inception,2010,Magnus Nolan,actor,James (20 months),15
1543390,Inception,2010,Yuji Okumoto,actor,Saito's Attendant,19
1642703,Inception,2010,Andrew Pleavin,actor,Businessman,47
1655286,Inception,2010,Pete Postlethwaite,actor,Maurice Fischer,10
1687264,Inception,2010,Marc Raducci,actor,Lobby Sub Con,39
1700316,Inception,2010,Dileep Rao,actor,Yusuf,6
1856902,Inception,2010,Felix Scott,actor,Businessman,46
2038151,Inception,2010,Jason Tendell,actor,Fischer's Driver,49
2053269,Inception,2010,Kraig Thornber,actor,Bar Sub Con,36
2178551,Inception,2010,Ken Watanabe,actor,Saito,5
2364024,Inception,2010,Natasha Beaumont,actress,Bar Sub Con,38
2496807,Inception,2010,Marion Cotillard,actress,Mal,9
2506047,Inception,2010,Helena Cullinan,actress,Penrose Sub Con,31
2533425,Inception,2010,Coralie Dedykere,actress,Bridge Sub Con,27
2643341,Inception,2010,Claire Geare,actress,Phillipa (3 years),14
2643349,Inception,2010,Taylor Geare,actress,Phillipa (5 years),16
2834321,Inception,2010,Silvie Laguna,actress,Bridge Sub Con,28
2840498,Inception,2010,Shelley Lang,actress,Penrose Sub Con,33
2879672,Inception,2010,Alex (II) Lombard,actress,Lobby Sub Con,42
2899268,Inception,2010,Jill Maddrell,actress,Lobby Sub Con,41
3002158,Inception,2010,Angela Nathenson,actress,Bar Sub Con,37
3016426,Inception,2010,Miranda Nolan,actress,Flight Attendant,22
3040332,Inception,2010,Ellen Page,actress,Ariadne,3
3090572,Inception,2010,Nicole Pulliam,actress,Lobby Sub Con,43
3115077,Inception,2010,Lisa (II) Reynolds,actress,Private Nurse,48
3121348,Inception,2010,Talulah Riley,actress,Blonde,25
3340154,Inception,2010,Shannon Welles,actress,Old Mal,51

In [77]:
len(inceptioners)

51

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [78]:
cast[(cast.title == "North by Northwest") & (cast.n.notnull())].sort_values('n')

,title,year,name,type,character,n
789998,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1
3154749,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2
1320849,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3
2838948,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4
322299,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5
2745218,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6
1537502,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7
1155311,North by Northwest,1959,Martin Landau,actor,Leonard,8
2215991,North by Northwest,1959,Adam Williams,actor,Valerian,9
1642042,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10
603354,North by Northwest,1959,Robert Ellenstein,actor,Licht,11
2078797,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12
420250,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13
1368049,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14
185152,North by Northwest,1959,Edward Binns,actor,Captain Junket,15
1255048,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [79]:
cast[(cast.title == "Sleuth") & (cast.year == 1972)].sort_values('n')

,title,year,name,type,character,n
1546535,Sleuth,1972,Laurence Olivier,actor,Andrew Wyke,1
294969,Sleuth,1972,Michael Caine,actor,Milo Tindle,2
337971,Sleuth,1972,Alec Cawthorne,actor,Inspector Doppler,3
1328287,Sleuth,1972,John (II) Matthews,actor,Detective Sergeant Tarrant,4
2460569,Sleuth,1972,Eve (III) Channing,actress,Marguerite Wyke,5
1313271,Sleuth,1972,Teddy Martin,actor,Police Constable Higgs,6

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [80]:
cast[(cast.title == "Sleuth") & (cast.year == 2007)].sort_values('n')

          title  year                 name     type          character   n
294970   Sleuth  2007        Michael Caine    actor             Andrew   1
1172161  Sleuth  2007             Jude Law    actor               Milo   2
1637144  Sleuth  2007        Harold Pinter    actor        Man on T.V.   3
233996   Sleuth  2007      Kenneth Branagh    actor  Other Man on T.V. NaN
337972   Sleuth  2007  Alec (II) Cawthorne    actor  Inspector Doppler NaN
2460568  Sleuth  2007    Eve (II) Channing  actress    Marguerite Wyke NaN
3025835  Sleuth  2007    Carmel O'Sullivan  actress             Maggie NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [81]:
hamlets = cast[(cast.title == "Hamlet") & (cast.year == 1921) & (cast.n.notnull())]
hamlets

          title  year                    name     type         character  n
6826     Hamlet  1921        Fritz Achterberg    actor       Fortinbras,  9
414828   Hamlet  1921            Paul Conradi    actor      K?nig Hamlet  2
502963   Hamlet  1921        Anton De Verdier    actor           Laertes  7
1030355  Hamlet  1921         Hans Junkermann    actor          Polonius  6
1979622  Hamlet  1921            Heinz Stieda    actor           Horatio  5
2150691  Hamlet  1921  Eduard von Winterstein    actor          Claudius  4
2407747  Hamlet  1921         Mathilde Brandt  actress  K?nigin Gertrude  3
2756997  Hamlet  1921          Lilly Jacobson  actress           Ophelia  8
3012392  Hamlet  1921            Asta Nielsen  actress            Hamlet  1

In [82]:
len(hamlets)

9

### How many roles were credited in Branagh’s 1996 Hamlet?

In [83]:
len(cast[(cast.title == "Hamlet") & (cast.year == 1996) & (cast.n.notnull())])

46

### How many "Hamlet" roles have been listed in all film credits through history?

In [84]:
len(cast[cast.character == "Hamlet"])

85

### How many people have played an "Ophelia"?

In [85]:
uniques = set(cast[cast.character == "Ophelia"].name)

In [86]:
len(uniques)

97

### How many people have played a role called "The Dude"?

In [87]:
dudes = cast[cast.character == "The Dude"].name
dudes

244911            Jeff Bridges
306518             Jordan Cann
451612           Scott Crowell
516657          Chris DeMarcus
553251             Mike Donlin
570475          Devin The Dude
989397     Matthew (XIX) James
1033579     Christopher Kadish
1239070       Jason Loughridge
1256738            Steve Lyons
1371915         Mark Alan Meek
1397617            Jerry Miley
1617721       House Peters Jr.
1666993        Jason Priestley
1994883           Bobby Styles
2114929        Dick Van Patten
2190305             Joel Weiss
Name: name, dtype: object

In [88]:
len(dudes)

17

### How many people have played a role called "The Stranger"?

In [89]:
strangers = cast[cast.character == "The Stranger"]
strangers

,title,year,name,type,character,n
22938,Theeb,2014,Hassan Mutlag Al-Maraiyeh,actor,The Stranger,3
31788,My Time to Die,2014,Vincent H. Alexander,actor,The Stranger,2
59979,Get Mean,1975,Tony Anthony,actor,The Stranger,1
59982,Lo straniero di silenzio,1968,Tony Anthony,actor,The Stranger,1
59984,Un dollaro tra i denti,1967,Tony Anthony,actor,The Stranger,1
59985,"Un uomo, un cavallo, una pistola",1967,Tony Anthony,actor,The Stranger,1
74013,Buzzy and the Phantom Pinto,1941,Phil Arnold,actor,The Stranger,10
110715,Hungry Man,2013,Cristi Balea,actor,The Stranger,NaN
125094,Trading Hearts,1988,Richard Baron,actor,The Stranger,5
126926,The Gospel of Us,2012,Nigel Barrett,actor,The Stranger,NaN
132842,Winning,1969,Harry Basch,actor,The Stranger,NaN
179718,Urban Odyssey,2010,Arben Biba,actor,The Stranger,12
187693,Suit of Lights,2014,Richard (XV) Bishop,actor,The Stranger,NaN
217299,Land o' Lizards,1916,Frank Borzage,actor,The Stranger,1
237597,Im Banne des Unheimlichen,1968,Pinkas Braun,actor,The Stranger,4
285935,Dear Frankie,2004,Gerard Butler,actor,The Stranger,15
334654,Forgiven This Gun4hire,2016,Nik Catello,actor,The Stranger,NaN
345871,My Little Sister,1919,Lyster Chambers,actor,The Stranger,5
356709,The Skip Thomas Project,2012,Michael V. Chastain,actor,The Stranger,NaN
359041,Lightning in a Bottle,2012,Chazz,actor,The Stranger,NaN
376658,"Winesburg, Ohio",2008,Alan Christy,actor,The Stranger,NaN
403059,Chicago Heights,2009,Jason (VII) Coleman,actor,The Stranger,NaN
420082,The Tomboy,1921,Hallam Cooley,actor,The Stranger,2
423872,Oldboy,2013,Sharlto Copley,actor,The Stranger,3
427682,Dead of the Night,2013,Ste Cork,actor,The Stranger,29
429409,Men,1924,Gino Corrado,actor,The Stranger,6
430188,Tennessee,2008,Harp Corrigan,actor,The Stranger,NaN
440106,Saddle Tramp,1950,Walter Coy,actor,The Stranger,14
446697,Sandra Munt,2016,Crimsaiz,actor,The Stranger,9
449931,The Yellow Sign,2001,Shawn Crosby,actor,The Stranger,NaN
...,...,...,...,...,...,...
1928485,The Adventures of Mark Twain,1985,Herb Smith,actor,The Stranger,8
1942854,Julia X,2011,Kevin Sorbo,actor,The Stranger,2
1951415,The Third Date,2003,Ron (III) Spencer,actor,The Stranger,5
1957634,Rites of Spring,2011,Marco St. John,actor,The Stranger,11
1989080,The Feud,1989,David Strathairn,actor,The Stranger,27
1991520,Backlash,1947,Leonard Strong,actor,The Stranger,5
2000940,Death and Taxis,2007,Suman,actor,The Stranger,NaN
2004957,The Killing Time,1987,Kiefer Sutherland,actor,The Stranger,2
2037766,A Slight Case of Murder,1938,Harry Tenbrook,actor,The Stranger,24
2043017,Little Lord Fauntleroy,1921,Arthur Thalasso,actor,The Stranger,8
2054771,The Traveler,2010,Zachary Throne,actor,The Stranger,NaN
2056879,Lie ri kuang feng ye huo,1980,Peng Tien,actor,The Stranger,1
2094399,Hogan's Alley,1925,Ben Turpin,actor,The Stranger,5
2113600,Secret of the Blue Room,1933,Anders Van Haden,actor,The Stranger,11
2117985,Alone (X),2014,Brian VanDyke,actor,The Stranger,NaN
2124727,The Passing of the Third Floor Back,1935,Conrad Veidt,actor,The Stranger,1
2145482,Horror Island,1941,Emmett Vogan,actor,The Stranger,12
2223088,Star Quest,2015,Ermal Williamson,actor,The Stranger,3
2228981,The Stranger,1920,Millard K. Wilson,actor,The Stranger,1
2233283,It All Happens Incredibly Fast,2003,Maurice Dean Wint,actor,The Stranger,NaN
2256647,Sunday in the Middle of Nowhere,2012,Steve Yahnke,actor,The Stranger,4
2259372,Mo sheng ren,1968,Peter Yang,actor,The Stranger,2
2262915,DBC III: A Saga,2014,Derrick Yeoman,actor,The Stranger,17
2518221,Ranchers and Rascals,1925,Patricia Darling,actress,The Stranger,6
2805553,"Silent Night, Bloody Night: The Homecoming",2013,Adrienne King,actress,The Stranger,NaN
2880666,The Stranger,1995,Kathy Long,actress,The Stranger,1
2893205,Ever Since Eve,1921,Ethel Lynne,actress,The Stranger,7
3056502,Weitertanzen,2008,Rosa Maria Paz,actress,The Stranger,NaN
3075815,The Godsend,1980,Angela Pleasence,actress,The Stranger,3
3197414,Motherland,1927,Dorinea Shirley,actress,The Stranger,NaN

In [90]:
len(strangers)

194

### How many roles has Sidney Poitier played throughout his career?

In [91]:
poitiers = cast[cast.name == "Sidney Poitier"]
poitiers

,title,year,name,type,character,n
1646411,A Patch of Blue,1965,Sidney Poitier,actor,Gordon Ralfe,1
1646412,A Piece of the Action,1977,Sidney Poitier,actor,Manny Durrell,1
1646413,A Raisin in the Sun,1961,Sidney Poitier,actor,Walter Lee Younger,1
1646414,A Warm December,1973,Sidney Poitier,actor,Dr. Matt Younger,1
1646415,All the Young Men,1960,Sidney Poitier,actor,Sgt. Eddie Towler,2
1646416,Band of Angels,1957,Sidney Poitier,actor,Rau-Ru,3
1646417,Blackboard Jungle,1955,Sidney Poitier,actor,Gregory W. Miller,10
1646418,Brother John,1971,Sidney Poitier,actor,John Kane,1
1646419,Buck and the Preacher,1972,Sidney Poitier,actor,Buck,1
1646420,"Cry, the Beloved Country",1951,Sidney Poitier,actor,Reverend Msimangu,3
1646421,Duel at Diablo,1966,Sidney Poitier,actor,Toller,2
1646422,Edge of the City,1957,Sidney Poitier,actor,Tommy Tyler,2
1646423,For Love of Ivy,1968,Sidney Poitier,actor,Jack Parks,1
1646424,Go Man Go,1954,Sidney Poitier,actor,Inman Jackson,3
1646425,"Good-bye, My Lady",1956,Sidney Poitier,actor,Gates Watson,4
1646426,Guess Who's Coming to Dinner,1967,Sidney Poitier,actor,John Prentice,2
1646427,In the Heat of the Night,1967,Sidney Poitier,actor,Virgil Tibbs,1
1646428,Let's Do It Again,1975,Sidney Poitier,actor,Clyde Williams,1
1646429,Lilies of the Field,1963,Sidney Poitier,actor,Homer Smith,1
1646430,Little Nikita,1988,Sidney Poitier,actor,Roy Parmenter,1
1646431,No Way Out,1950,Sidney Poitier,actor,Dr. Luther Brooks,4
1646432,Paris Blues,1961,Sidney Poitier,actor,Eddie Cook,3
1646433,Porgy and Bess,1959,Sidney Poitier,actor,Porgy,1
1646434,Pressure Point,1962,Sidney Poitier,actor,Doctor,1
1646435,Red Ball Express,1952,Sidney Poitier,actor,Robertson,5
1646436,Sepia Cinderella,1947,Sidney Poitier,actor,Night Club Extra,NaN
1646437,Shoot to Kill,1988,Sidney Poitier,actor,Warren Stantin,1
1646438,Sneakers,1992,Sidney Poitier,actor,Donald Crease,4
1646439,Something of Value,1957,Sidney Poitier,actor,Kimani Wa Karanja,13
1646440,The Bedford Incident,1965,Sidney Poitier,actor,Ben Munceford,2
1646441,The Defiant Ones,1958,Sidney Poitier,actor,Noah Cullen,2
1646442,The Greatest Story Ever Told,1965,Sidney Poitier,actor,Simon of Cyrene,21
1646443,The Jackal,1997,Sidney Poitier,actor,FBI Deputy Director Carter Preston,3
1646444,The Long Ships,1964,Sidney Poitier,actor,Aly Mansuh,2
1646445,The Lost Man,1969,Sidney Poitier,actor,Jason Higgs,1
1646446,The Mark of the Hawk,1957,Sidney Poitier,actor,Obam,2
1646447,The Organization,1971,Sidney Poitier,actor,Virgil Tibbs,1
1646448,The Slender Thread,1965,Sidney Poitier,actor,Alan Newell,1
1646449,The Wilby Conspiracy,1975,Sidney Poitier,actor,Shack Twala,1
1646450,They Call Me Mister Tibbs!,1970,Sidney Poitier,actor,Virgil Tibbs,1
1646451,"To Sir, with Love",1967,Sidney Poitier,actor,Mark Thackeray,1
1646452,Uptown Saturday Night,1974,Sidney Poitier,actor,Steve Jackson,1
1646453,Virgin Island,1958,Sidney Poitier,actor,Marcus,3

In [92]:
len(poitiers)

43

### How many roles has Judi Dench played?

In [93]:
denches = cast[cast.name == "Judi Dench"]
denches

,title,year,name,type,character,n
2539418,84 Charing Cross Road,1987,Judi Dench,actress,Nora Doel,3
2539419,A Handful of Dust,1988,Judi Dench,actress,Mrs. Beaver,13
2539420,A Midsummer Night's Dream,1968,Judi Dench,actress,Titania,16
2539421,A Room with a View,1985,Judi Dench,actress,"Eleanor Lavish, a novelist",7
2539422,A Study in Terror,1965,Judi Dench,actress,Sally,8
2539423,Angelina Ballerina: Angelina Sets Sail,2006,Judi Dench,actress,Miss Lilly,2
2539424,Casino Royale,2006,Judi Dench,actress,M,4
2539425,Chocolat,2000,Judi Dench,actress,Armande Voizin,18
2539426,Dead Cert,1974,Judi Dench,actress,Laura Davidson,2
2539427,Die Another Day,2002,Judi Dench,actress,M,6
2539428,Doogal,2006,Judi Dench,actress,Narrator,7
2539429,Four in the Morning,1965,Judi Dench,actress,Wife,2
2539430,GoldenEye,1995,Judi Dench,actress,M,6
2539431,Hamlet,1996,Judi Dench,actress,Hecuba,12
2539432,He Who Rides a Tiger,1965,Judi Dench,actress,Joanne,2
2539433,Henry V,1989,Judi Dench,actress,Mistress Nell Quickly,26
2539434,Home on the Range,2004,Judi Dench,actress,Mrs. Caloway,7
2539435,Iris,2001,Judi Dench,actress,Iris Murdoch,3
2539436,J. Edgar,2011,Judi Dench,actress,Annie Hoover,13
2539437,Jack & Sarah,1995,Judi Dench,actress,Margaret,3
2539438,Jane Eyre,2011,Judi Dench,actress,Mrs. Fairfax,18
2539439,Ladies in Lavender,2004,Judi Dench,actress,Ursula,1
2539440,Luther,1974,Judi Dench,actress,Katherine,7
2539441,Miss Peregrine's Home for Peculiar Children,2016,Judi Dench,actress,Miss Avocet,NaN
2539442,Mrs Brown,1997,Judi Dench,actress,Queen Victoria,1
2539443,Mrs Henderson Presents,2005,Judi Dench,actress,Mrs. Laura Henderson,1
2539444,My Week with Marilyn,2011,Judi Dench,actress,Dame Sybil Thorndike,23
2539445,Nine,2009,Judi Dench,actress,Lilli,6
2539446,Notes on a Scandal,2006,Judi Dench,actress,Barbara Covett,1
2539447,Philomena,2013,Judi Dench,actress,Philomena,1
2539448,Pirates of the Caribbean: On Stranger Tides,2011,Judi Dench,actress,Society Lady,16
2539449,Pride & Prejudice,2005,Judi Dench,actress,Lady Catherine de Bourg,20
2539450,Quantum of Solace,2008,Judi Dench,actress,M,4
2539451,Rage,2009,Judi Dench,actress,Mona Carvell,NaN
2539452,Run for Your Wife,2012,Judi Dench,actress,Bag Lady,40
2539453,Schadenfreude,2016,Judi Dench,actress,The Narrator,NaN
2539454,Shakespeare in Love,1998,Judi Dench,actress,Queen Elizabeth,12
2539455,Skyfall,2012,Judi Dench,actress,M,2
2539456,Spectre,2015,Judi Dench,actress,M (Barbara Mawdsley),NaN
2539457,Stars in Shorts,2012,Judi Dench,actress,Mary,29
2539458,Tea with Mussolini,1999,Judi Dench,actress,Arabella,2
2539459,The Angelic Conversation,1985,Judi Dench,actress,Shakespeare's Sonnets read by,3
2539460,The Best Exotic Marigold Hotel,2011,Judi Dench,actress,Evelyn Greenslade,1
2539461,The Chronicles of Riddick,2004,Judi Dench,actress,Aereon,4
2539462,The Importance of Being Earnest,2002,Judi Dench,actress,Lady Bracknell,5
2539463,The Second Best Exotic Marigold Hotel,2015,Judi Dench,actress,Evelyn Greenslade,5
2539464,The Shipping News,2001,Judi Dench,actress,Agnis Hamm,3
2539465,The Third Secret,1964,Judi Dench,actress,Miss Humphries,12
2539466,The World Is Not Enough,1999,Judi Dench,actress,M,6
2539467,Tomorrow Never Dies,1997,Judi Dench,actress,M,9
2539468,Tulip Fever,2016,Judi Dench,actress,The Abbess of St. Ursula,NaN
2539469,Wetherby,1985,Judi Dench,actress,Marcia Pilborough,3

In [94]:
len(denches)

52

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [95]:
cast[(cast.year >= 1940) & (cast.year <= 1949) & (cast.name == "Cary Grant") & (cast.n == 2)]

                   title  year        name   type    character  n
789995  My Favorite Wife  1940  Cary Grant  actor         Nick  2
790005    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [96]:
cast[(cast.year >= 1940) & (cast.year <= 1949) & (cast.name == "Cary Grant") & (cast.n == 1)].sort_values('year')

,title,year,name,type,character,n
790020,The Howards of Virginia,1940,Cary Grant,actor,Matt Howard,1
789977,His Girl Friday,1940,Cary Grant,actor,Walter Burns,1
790022,The Philadelphia Story,1940,Cary Grant,actor,C. K. Dexter Haven,1
790010,Suspicion,1941,Cary Grant,actor,Johnnie,1
790024,The Talk of the Town,1942,Cary Grant,actor,Leopold Dilg,1
790001,Once Upon a Honeymoon,1942,Cary Grant,actor,Patrick 'Pat' O'Toole,1
789968,Destination Tokyo,1943,Cary Grant,actor,Capt. Cassidy,1
789993,Mr. Lucky,1943,Cary Grant,actor,Joe Adams,1
789994,Mr. Lucky,1943,Cary Grant,actor,Joe Bascopolous,1
790002,Once Upon a Time,1944,Cary Grant,actor,Jerry Flynn,1
789960,Arsenic and Old Lace,1944,Cary Grant,actor,Mortimer Brewster,1
789997,None But the Lonely Heart,1944,Cary Grant,actor,Ernie Mott,1
789996,Night and Day,1946,Cary Grant,actor,Cole Porter,1
789999,Notorious,1946,Cary Grant,actor,Devlin,1
790016,The Bachelor and the Bobby-Soxer,1947,Cary Grant,actor,Dick Nugent,1
790017,The Bishop's Wife,1947,Cary Grant,actor,Dudley,1
789992,Mr. Blandings Builds His Dream House,1948,Cary Grant,actor,Jim Blandings,1
789972,Every Girl Should Be Married,1948,Cary Grant,actor,Dr. Madison Brown,1
789981,I Was a Male War Bride,1949,Cary Grant,actor,Capt. Henri Rochard,1

### How many roles were available for actors in the 1950s?

In [97]:
roles = cast[(cast.year >= 1950) & (cast.year <= 1959) & (cast.type == 'actor')]
roles

,title,year,name,type,character,n
60,Fire Down Below,1957,'Stretch' Cox Troupe,actor,Limbo Dance by,20
62,Dorp aan de rivier,1958,Frans 't Hoen,actor,Dirk Jan,15
104,Die Todesarena,1953,Die 3 Motorellos,actor,Themselves,NaN
230,Palletoori Pilla,1950,Subba Rao A.V.,actor,Kampanna Dora,4
231,Sri Kalahastiswara Mahatyam,1954,Subba Rao A.V.,actor,Basavareddy,12
243,Brudebuketten,1953,Per Aabel,actor,H?yland jr.,3
247,The President's Lady,1953,Linus Aaberg,actor,Uncle Alfred,NaN
304,Bigger Than Life,1956,Dee Aaker,actor,Joe,NaN
305,Mister Scoutmaster,1953,Dee Aaker,actor,Bit Role,NaN
306,Spin and Marty: The Movie,1955,Dee Aaker,actor,Russel the Muscle,13
307,The Kid from Left Field,1953,Dee Aaker,actor,3rd Baseman,NaN
309,A Lion Is in the Streets,1953,Lee Aaker,actor,Johnny Briscoe,NaN
310,Arena,1953,Lee Aaker,actor,Teddy Hutchins,7
311,Black Tuesday,1954,Lee Aaker,actor,Little Boy,NaN
313,Desperate Search,1952,Lee Aaker,actor,Don Heldon,6
314,Destry,1954,Lee Aaker,actor,Eli Skinner,13
315,Full House,1952,Lee Aaker,actor,"J.B. Dorset aka Red Chief (segment ""The Ransom...",14
316,Hans Christian Andersen,1952,Lee Aaker,actor,Little Boy,NaN
317,Her Twelve Men,1954,Lee Aaker,actor,Michael Elliott,NaN
318,High Noon,1952,Lee Aaker,actor,Boy,NaN
319,Hondo,1953,Lee Aaker,actor,Johnny Lowe,9
320,Jeopardy,1953,Lee Aaker,actor,Bobby Stilwin,4
321,Mister Scoutmaster,1953,Lee Aaker,actor,Arthur,11
322,My Son John,1952,Lee Aaker,actor,Boy,NaN
323,No Room for the Groom,1952,Lee Aaker,actor,Donovan,8
324,Ricochet Romance,1954,Lee Aaker,actor,Timmy Williams,10
325,Ride Clear of Diablo,1954,Lee Aaker,actor,Boy,NaN
326,Something to Live For,1952,Lee Aaker,actor,Alternate Boy,NaN
327,Take Me to Town,1953,Lee Aaker,actor,Corney Hall,5
328,The Atomic City,1952,Lee Aaker,actor,Tommy Addison,5
...,...,...,...,...,...,...
2291882,Ninkyo Tokaido,1958,Ry?tar? ?tomo,actor,Omasa,NaN
2291883,Ohtori-jo hanayome,1958,Ry?tar? ?tomo,actor,Gentaro,NaN
2291891,Bijo to ekitai ningen,1958,Shin ?tomo,actor,"Hamano, nightclub gangster",29
2291893,Kakushi-toride no san-akunin,1958,Shin ?tomo,actor,Samurai on horseback,32
2291901,Shichinin no samurai,1954,Shin ?tomo,actor,Bandit Second-in-Command,25
2291935,Shichinin no samurai,1954,Hideo ?tsuka,actor,Farmer,72
2291951,Arashi,1956,Kunio ?tsuka,actor,Jiro Mizusawa,7
2291973,Chijo,1957,Kenji ?yama,actor,T?yama - mayor,NaN
2291977,Hyoheki,1958,Kenji ?yama,actor,Managing Director Tokimatsu,10
2292004,Drakula Istanbul'da,1953,Kadri ?gelman,actor,Usak,7
2292144,Restaurant Intim,1950,Steinar ?ster,actor,Cook,NaN
2292146,Flicka utan namn,1954,Bertil ?sterberg,actor,Himself - F?rsvarsadvokaten,25
2292177,Alla tiders 91 Karlsson,1953,Alf ?stlund,actor,Viking,11
2292178,"Blondie, Biffen och Bananen",1952,Alf ?stlund,actor,Speculative buyer,NaN
2292179,Den vita katten,1950,Alf ?stlund,actor,Ticket Collector,15
2292181,Flicka och hyacinter,1950,Alf ?stlund,actor,Viktor Ekberg,NaN
2292183,Jazzgossen,1958,Alf ?stlund,actor,Jazzgosse,26
2292184,Medan staden sover,1950,Alf ?stlund,actor,Andersson,NaN
2292185,Nattens ljus,1957,Alf ?stlund,actor,Gentleman whose car is stolen,18
2292186,Restaurant Intim,1950,Alf ?stlund,actor,Manager Nessing,15
2292189,Tull-Bom,1951,Alf ?stlund,actor,Skakis,10
2292190,Ursula - Flickan i Finnskogarna,1953,Alf ?stlund,actor,"Svensson, court janitor",18
2292251,Ak altin,1957,Turgut ?zatay,actor,Idris,4
2292266,Kara talih,1957,Turgut ?zatay,actor,Riza,1
2292282,Yalnizlar rihtimi,1959,Turgut ?zatay,actor,Ali,3
2292439,Bulgar Sadik,1954,Mahir ?zerdem,actor,Y?zbasi Avni,2
2292498,Kalbimin sarkisi,1956,M?nir ?zkul,actor,M?nir,2
2292730,Salve sauegjeter,1958,?yvind ?yen,actor,"Asbj?rn, sauegjeter",2
2292738,La noche avanza,1952,Francisco ?beda,actor,Pelotari,21
2292881,Kara Efe,1952,Ali ?st?ntas,actor,Kara Efe,1

In [98]:
len(roles)

150124

### How many roles were avilable for actresses in the 1950s?

In [99]:
len(cast[(cast.year >= 1950) & (cast.year <= 1959) & (cast.type == 'actress')])

54588

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [100]:
leads = cast[(cast.year <= 1980) & (cast.n == 1)]
leads

,title,year,name,type,character,n
240,En glad gutt,1932,Hauk Aabel,actor,Ola Nordistua,1
917,Batman Fights Dracula,1967,Jing Abalos,actor,Batman,1
918,Batman Fights Dracula,1967,Jing Abalos,actor,Bruce Wayne,1
922,Mighty Rock,1969,Jing Abalos,actor,Mighty Rock,1
1001,"Ar Daijero, Rom agar var",1975,Dodo Abashidze,actor,Mikho,1
1006,Didi mtsvane veli,1967,Dodo Abashidze,actor,Sosana,1
1011,Kvarkvare,1978,Dodo Abashidze,actor,Kvarkavre Tutaberi,1
1018,Pirveli mertskhali,1975,Dodo Abashidze,actor,Jasoni,1
1021,Sinatle chvens panjrebshi,1969,Dodo Abashidze,actor,Aleqsandre,1
1026,Tsimbireli papa,1974,Dodo Abashidze,actor,Nestor,1
1033,Glakhis naambobi,1961,Gocha Abashidze,actor,Gabro,1
1098,Il pap'occhio,1980,Diego Abatantuono,actor,Padre Gabriele,1
1242,Athkiya' laken aghbiya',1980,Rushdy Abaza,actor,Hamdi,1
1247,El mushajibun,1966,Rushdy Abaza,actor,Amin,1
1473,Bir qalanin sirri,1959,Gyunduz Abbasov,actor,Elsan,1
1579,Il pleut sur Santiago,1975,John Abbey,actor,L'agent am?ricain,1
1580,Il pleut sur Santiago,1975,John Abbey,actor,CIA Agent,1
1698,Abbott and Costello Go to Mars,1953,Bud Abbott,actor,Lester,1
1699,Abbott and Costello in the Foreign Legion,1950,Bud Abbott,actor,Bud Jones,1
1700,Abbott and Costello Meet Captain Kidd,1952,Bud Abbott,actor,Rocky Stonebridge,1
1701,Abbott and Costello Meet Dr. Jekyll and Mr. Hyde,1953,Bud Abbott,actor,Slim,1
1702,Abbott and Costello Meet the Invisible Man,1951,Bud Abbott,actor,Bud Alexander,1
1703,Abbott and Costello Meet the Keystone Kops,1955,Bud Abbott,actor,Harry 'Slim' Pierce,1
1704,"Abbott and Costello Meet the Killer, Boris Kar...",1949,Bud Abbott,actor,Casey Edwards,1
1705,Abbott and Costello Meet the Mummy,1955,Bud Abbott,actor,Pete Patterson,1
1706,Africa Screams,1949,Bud Abbott,actor,Buzz Johnson,1
1707,Buck Privates,1941,Bud Abbott,actor,Slicker Smith,1
1708,Buck Privates Come Home,1947,Bud Abbott,actor,Slicker Smith,1
1709,Bud Abbott and Lou Costello in Hollywood,1945,Bud Abbott,actor,Buzz Kurtis,1
1710,Bud Abbott Lou Costello Meet Frankenstein,1948,Bud Abbott,actor,Chick,1
...,...,...,...,...,...,...
3385480,I Married a Savage,1949,Zorita,actress,Zorita,1
3385591,Alena,1947,Miluse Zoubkov?,actress,Alena,1
3385596,Diogmos,1964,Voula Zouboulaki,actress,Katerina Rodeli,1
3385600,"Ohi, ...kyrie Johnson",1965,Voula Zouboulaki,actress,Eleni,1
3385602,Syntomo dialeimma,1966,Voula Zouboulaki,actress,Emma Karali,1
3385635,Le lit de la vierge,1971,Zouzou,actress,Marie,1
3385636,Le lit de la vierge,1971,Zouzou,actress,Marie Magdal?ne,1
3385637,Les apprentis sorciers,1977,Zouzou,actress,Clara,1
3385728,A hierro muere,1962,Olga Zubarry,actress,Elisa,1
3385732,El vampiro negro,1953,Olga Zubarry,actress,Amalia,1
3385733,El vampiro negro,1953,Olga Zubarry,actress,Rita,1
3385735,La muerte camina en la lluvia,1948,Olga Zubarry,actress,Lila Espinoza,1
3385738,Marianela,1955,Olga Zubarry,actress,Marianela,1
3385739,Valentina,1950,Olga Zubarry,actress,Valentina Gonz?lez Garc?a,1
3385747,Gul-e-Bakavali,1924,Zubeida,actress,Bakavali,1
3386252,Cvetje v jeseni,1973,Milena Zupancic,actress,Meta,1
3386270,Vdovstvo Karoline Zasler,1976,Milena Zupancic,actress,Karolina Zasler,1
3386724,Strach,1975,Joanna Z?lkowska,actress,Agnieszka Pawelczyk,1
3386748,El secreto del doctor,1930,Eugenia Z?ffoli,actress,Lillian Garson,1
3386776,"Sutyi, a szerencsegyerek",1938,Kl?ri ?d?m,actress,Sutyl,1
3386780,Hoheit tanzt Walzer,1935,Ir?n ?gay,actress,Prinzessin Marika,1
3386873,Antonia Santos,1944,Lily (II) ?lvarez,actress,Antonia Santos,1
3386945,Flor de fango,1942,Sof?a ?lvarez,actress,Marissa,1
3386946,La barca de oro,1947,Sof?a ?lvarez,actress,Chabela Vargas,1
3386949,Soy charro de Rancho Grande,1947,Sof?a ?lvarez,actress,Cristina,1
3387202,La nuit de Sybille,1947,Paulette ?lambert,actress,Sibylle,1
3387273,Anego,1969,Hiroko ?gi,actress,Ai Konno,1
3387274,Noboriryu tekkahada,1970,Hiroko ?gi,actress,Katsumi Sakura,1
3387467,Kvinnolek,1968,Gunbritt ?hrstr?m,actress,"Lisa Holmberg, fashion designer",1
3387509,Tamam mi devam mi?,1975,F?sun ?nal,actress,F?sun,1

In [101]:
len(leads)

61979

### How many non-leading roles were available through from the beginning of film history through 1980?

In [102]:
others = cast[(cast.year <= 1980) & (cast.n != 1)]
others

,title,year,name,type,character,n
25,Los tarantos,1963,'El Guisa',actor,Bailaor,25
28,Los tarantos,1963,'El Viti',actor,Cantaor,20
35,Been Down So Long It Looks Like Up to Me,1971,Murray the 'K',actor,Himself,NaN
36,I Wanna Hold Your Hand,1978,Murray the 'K',actor,Himself,47
37,That's the Way of the World,1975,Murray the 'K',actor,Big John Little,22
48,In the Land of the Head Hunters,1914,Paddy 'Malid,actor,Kenada,5
50,Los tarantos,1963,'Morita',actor,Cantaor,18
51,Los tarantos,1963,'Pucherete',actor,Guitarist,14
60,Fire Down Below,1957,'Stretch' Cox Troupe,actor,Limbo Dance by,20
61,De zaak M.P.,1960,Frans 't Hoen,actor,Hollandse boer,29
62,Dorp aan de rivier,1958,Frans 't Hoen,actor,Dirk Jan,15
90,Wild Wheels,1969,13th Committee,actor,Themselves,11
94,C.B. Hustlers,1976,The 18 Wheelers of Interstate 5,actor,The 18 Wheelers of Interstate 5,11
99,Atemlos vor Liebe,1970,Ballett 2000,actor,Themselves,NaN
101,Thunder in Carolina,1960,2nd Marine Division Band,actor,Themselves,NaN
104,Die Todesarena,1953,Die 3 Motorellos,actor,Themselves,NaN
119,Schatten der Manege,1931,5 Artonis,actor,Themselves - Artists,NaN
151,I ragazzi di Bandiera Gialla,1968,Equipe 84,actor,Themselves,14
176,Cheech and Chong's Next Movie,1980,Bobby A.,actor,Doorman,33
229,Sri Venkateswara Mahatmyam,1960,Subba Rao A.V. Jr.,actor,Brahma,10
230,Palletoori Pilla,1950,Subba Rao A.V.,actor,Kampanna Dora,4
231,Sri Kalahastiswara Mahatyam,1954,Subba Rao A.V.,actor,Basavareddy,12
232,Sri Venkateswara Mahatmyam,1960,Subba Rao A.V.,actor,Akasa Raju,5
237,Kampen om tungtvannet,1948,Andreas Aabel,actor,Kasper Idland - fenrik,8
238,Alexander den Store,1917,Hauk Aabel,actor,Alexander Nyberg,NaN
239,Du har lovet mig en kone!,1935,Hauk Aabel,actor,Professoren,6
241,Troll-Elgen,1927,Hauk Aabel,actor,"Piper, direkt?r",9
242,Ungen,1938,Hauk Aabel,actor,Krestoffer,8
243,Brudebuketten,1953,Per Aabel,actor,H?yland jr.,3
244,Big Wednesday,1978,Dennis Aaberg,actor,Slick,14
...,...,...,...,...,...,...
3387674,Reyhan,1969,Nermin ?zses,actress,Kumarbaz,NaN
3387675,Ruya gibi,1971,Nermin ?zses,actress,Ev Sahibi,NaN
3387676,Sabikali,1974,Nermin ?zses,actress,Gardiyan,NaN
3387677,Sev Kardesim,1972,Nermin ?zses,actress,Mahalleli,NaN
3387678,Sevmek,1974,Nermin ?zses,actress,Hafize,NaN
3387679,Topal,1973,Nermin ?zses,actress,M?sl?m'?n Annesi,NaN
3387680,Urfa-Istanbul,1968,Nermin ?zses,actress,Hemsire,NaN
3387702,Kafkas kartali,1968,Leman ?zt?rk,actress,Tatyana,11
3387721,4 x 4,1965,Kari ?hrn Geelmuyden,actress,Vibeke (Pike med hvit ball),NaN
3387722,Jeg drepte!,1942,Synn?ve ?ian,actress,"Berit, sykes?ster",10
3387727,Omringet,1960,Kari ?ksnevad,actress,Anne Aulie,2
3387728,Pastor Jarman kommer hjem,1958,Kari ?ksnevad,actress,Jarmans kone,11
3387773,Villmarkens lov,1944,Manina ?stvig,actress,Oppasserens hustru,8
3387774,Det var paa Rundetaarn,1955,Clara ?st?,actress,"Fru Hambro, deres v?rtinde",3
3387775,En ganske almindelig pige,1940,Clara ?st?,actress,Frk. Stjerneborg,6
3387776,Jeg elsker dig,1957,Clara ?st?,actress,Frk. Muhs,9
3387777,Rend mig i traditionerne,1979,Clara ?st?,actress,Patient,22
3387778,Styrmand Karlsen,1958,Clara ?st?,actress,Dronning Viktoria,9
3387779,Styrmand Karlsen,1958,Clara ?st?,actress,The Queen,9
3387780,Tante Cramers testamente,1941,Clara ?st?,actress,Husassistent Erna Nielsen,12
3387781,Tre piger fra Jylland,1957,Clara ?st?,actress,Frk. Lind,9
3387782,Ud i den kolde sne,1934,Clara ?st?,actress,Den fredgene pige,13
3387787,Unge hjerter,1917,Hildur ?verland,actress,Prestens husholderske,7
3387788,Line,1961,Olava ?verland,actress,A passenger,18
3387792,Toya,1956,Aslaug ?ye,actress,moren til Trygve,19
3387798,Venner,1960,Bibba ?ygard,actress,Kontordame,NaN
3387801,Bang!,1977,Beate ?rskov,actress,Beate,NaN
3387802,Alin yazisi,1972,?lk? ?lker,actress,Aynur,9
3387803,Tokmak Nuri,1975,?lk? ?lker,actress,Hemsire,NaN
3387805,Akdeniz korsanlari,1950,Muazzez ?lkerer,actress,Maria,2

In [103]:
len(others)

1061496

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [104]:
len(cast[(cast.year <= 1980) & (cast.n.isnull())])

422512