In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import sklearn as sklearn
import matplotlib as pyplot

/Users/xeinos/anaconda2/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [7]:
ldf = pd.read_csv("data/LoanStats3a.csv", header=1)
ldf.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [64]:
datadict = pd.read_excel("LCDataDictionary.xslx")
datadict

,LoanStatNew,Description
0,acc_now_delinq,The number of accounts on which the borrower i...
1,acc_open_past_24mths,Number of trades opened in past 24 months.
2,addr_state,The state provided by the borrower in the loan...
3,all_util,Balance to credit limit on all trades
4,annual_inc,The self-reported annual income provided by th...
5,annual_inc_joint,The combined self-reported annual income provi...
6,application_type,Indicates whether the loan is an individual ap...
7,avg_cur_bal,Average current balance of all accounts
8,bc_open_to_buy,Total open to buy on revolving bankcards.
9,bc_util,Ratio of total current balance to high credit/...
10,chargeoff_within_12_mths,Number of charge-offs within 12 months
11,collection_recovery_fee,post charge off collection fee
12,collections_12_mths_ex_med,Number of collections in 12 months excluding m...
13,delinq_2yrs,The number of 30+ days past-due incidences of ...
14,delinq_amnt,The past-due amount owed for the accounts on w...
15,desc,Loan description provided by the borrower
16,dti,A ratio calculated using the borrowerâ€™s total ...
17,dti_joint,A ratio calculated using the co-borrowers' tot...
18,earliest_cr_line,The month the borrower's earliest reported cre...
19,emp_length,Employment length in years. Possible values ar...
20,emp_title,The job title supplied by the Borrower when ap...
21,fico_range_high,The upper boundary range the borrowerâ€™s FICO a...
22,fico_range_low,The lower boundary range the borrowerâ€™s FICO a...
23,funded_amnt,The total amount committed to that loan at tha...
24,funded_amnt_inv,The total amount committed by investors for th...
25,grade,LC assigned loan grade
26,home_ownership,The home ownership status provided by the borr...
27,id,A unique LC assigned ID for the loan listing.
28,il_util,Ratio of total current balance to high credit/...
29,initial_list_status,The initial listing status of the loan. Possib...
...,...,...
87,purpose,A category provided by the borrower for the lo...
88,pymnt_plan,Indicates if a payment plan has been put in pl...
89,recoveries,post charge off gross recovery
90,revol_bal,Total credit revolving balance
91,revol_util,"Revolving line utilization rate, or the amount..."
92,sub_grade,LC assigned loan subgrade
93,tax_liens,Number of tax liens
94,term,The number of payments on the loan. Values are...
95,title,The loan title provided by the borrower
96,tot_coll_amt,Total collection amounts ever owed
97,tot_cur_bal,Total current balance of all accounts
98,tot_hi_cred_lim,Total high credit/credit limit
99,total_acc,The total number of credit lines currently in ...
100,total_bal_ex_mort,Total credit balance excluding mortgage
101,total_bal_il,Total current balance of all installment accounts
102,total_bc_limit,Total bankcard high credit/credit limit
103,total_cu_tl,Number of finance trades
104,total_il_high_credit_limit,Total installment high credit/credit limit
105,total_pymnt,Payments received to date for total amount funded
106,total_pymnt_inv,Payments received to date for portion of total...
107,total_rec_int,Interest received to date
108,total_rec_late_fee,Late fees received to date
109,total_rec_prncp,Principal received to date
110,total_rev_hi_lim,Total revolving high credit/credit limit
111,url,URL for the LC page with listing data.
112,verification_status,"Indicates if income was verified by LC, not ve..."
113,verified_status_joint,Indicates if the co-borrowers' joint income wa...
114,zip_code,The first 3 numbers of the zip code provided b...
115,NaN,NaN
116,NaN,* Employer Title replaces Employer Name for al...

In [8]:
rdf = pd.read_csv("data/RejectStatsA.csv", header=1)
rdf.head(10)

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0
5,15000.0,2007-05-27,Trinfiniti,645.0,0%,105xx,NY,3 years,0
6,10000.0,2007-05-27,NOTIFYi Inc,693.0,10%,210xx,MD,< 1 year,0
7,3900.0,2007-05-27,For Justin.,700.0,10%,469xx,IN,2 years,0
8,3000.0,2007-05-28,title?,694.0,10%,808xx,CO,4 years,0
9,2500.0,2007-05-28,timgerst,573.0,11.76%,407xx,KY,4 years,0

In [9]:
print len(rdf)

755441

In [10]:
ldf1 = pd.read_csv("data/LoanStats3b.csv", header=1)
ldf1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,10129403,11981032.0,7550.0,7550.0,7550.0,36 months,16.24%,266.34,C,C5,...,0.0,0.0,100.0,100.0,0.0,0.0,8000.0,5759.0,4000.0,0.0
1,10149342,12000897.0,27050.0,27050.0,27050.0,36 months,10.99%,885.46,B,B2,...,0.0,1.0,100.0,25.0,0.0,0.0,138554.0,70186.0,35700.0,33054.0
2,10159584,12011200.0,9750.0,9750.0,9750.0,36 months,13.98%,333.14,C,C1,...,0.0,2.0,100.0,66.7,0.0,0.0,21314.0,14123.0,7200.0,6214.0
3,10159498,1319523.0,12000.0,12000.0,12000.0,36 months,6.62%,368.45,A,A2,...,0.0,2.0,95.5,0.0,0.0,0.0,333044.0,42603.0,52600.0,42769.0
4,10129506,11981122.0,20800.0,20800.0,20800.0,36 months,13.53%,706.16,B,B5,...,0.0,3.0,90.2,50.0,0.0,0.0,43100.0,23473.0,15000.0,0.0

In [13]:
loans = pd.concat([ldf, ldf1], axis=0)
loans

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
5,1075269,1311441.0,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6,1069639,1304742.0,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
7,1072053,1288686.0,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
8,1071795,1306957.0,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
9,1071570,1306721.0,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
10,1070078,1305201.0,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
11,1069908,1305008.0,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12,1064687,1298717.0,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13,1069866,1304956.0,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14,1069057,1303503.0,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,1069759,1304871.0,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,1065775,1299699.0,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
17,1069971,1304884.0,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
18,1062474,1294539.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19,1069742,1304855.0,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
20,1069740,1284848.0,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
21,1039153,1269083.0,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
22,1069710,1304821.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
23,1069700,1304810.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,1069559,1304634.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
25,1069697,1273773.0,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
26,1069800,1304679.0,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
27,1069657,1304764.0,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
28,1069799,1304678.0,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
29,1047704,1278806.0,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188095,1066540,1300919.0,16400.0,16400.0,16400.000000,36 months,16.29%,578.93,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188096,1066264,1300628.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188097,1066384,1300345.0,15000.0,15000.0,15000.000000,36 months,6.03%,456.54,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188098,1059334,1291137.0,35000.0,35000.0,33429.996633,60 months,13.49%,805.17,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188099,1057322,1288885.0,12000.0,12000.0,12000.000000,36 months,6.03%,365.23,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188100,1065469,1299578.0,20750.0,20750.0,20725.000000,60 months,12.42%,465.99,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188101,1065451,1299555.0,22000.0,22000.0,22000.000000,60 months,12.42%,494.06,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188102,1065594,1299493.0,6600.0,6600.0,6600.000000,60 months,17.58%,166.10,D,D4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188103,1065309,1299395.0,22000.0,22000.0,22000.000000,60 months,14.65%,519.35,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188104,1065073,1299139.0,7500.0,7500.0,7500.000000,36 months,6.03%,228.27,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188105,1065066,1299132.0,33950.0,33950.0,31311.688766,60 months,15.96%,824.88,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188106,1064860,1298707.0,4000.0,4000.0,4000.000000,36 months,14.65%,137.98,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188107,1064243,1298032.0,18000.0,18000.0,10075.000000,60 months,22.35%,500.73,F,F5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188108,1064827,1298668.0,10000.0,10000.0,10000.000000,36 months,9.91%,322.25,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188109,997758,1222885.0,35000.0,21775.0,20375.659759,60 months,22.74%,610.60,G,G1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188110,1042487,1272771.0,20000.0,13675.0,6675.000000,60 months,19.91%,361.62,E,E4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188111,1063722,1296291.0,18000.0,18000.0,16737.957469,60 months,17.58%,452.98,D,D4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188112,1063649,1296212.0,17500.0,16800.0,16775.000000,60 months,22.74%,471.10,G,G1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188113,1062754,1295040.0,35000.0,22550.0,22550.000000,60 months,14.27%,527.87,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188114,1061393,1293181.0,24000.0,24000.0,22961.954975,60 months,12.69%,542.28,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188115,1061272,1293083.0,8650.0,8650.0,8625.000000,36 months,14.65%,298.38,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188116,1062334,1294400.0,20000.0,12675.0,12675.000000,60 months,14.27%,296.71,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188117,1062337,1294403.0,12000.0,12000.0,11975.000000,36 months,7.90%,375.49,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188118,1062400,1294262.0,20500.0,20500.0,20500.000000,36 months,16.77%,728.54,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188119,1059394,1291010.0,15000.0,15000.0,15000.000000,36 months,15.27%,521.97,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188120,1059224,1290827.0,35000.0,35000.0,35000.000000,36 months,15.96%,1229.81,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188121,1058722,1290521.0,12000.0,12000.0,12000.000000,36 months,16.29%,423.61,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188122,1058291,1289878.0,12000.0,7775.0,7775.000000,60 months,15.27%,186.08,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
188123,Total amount funded in policy code 1: 2700420250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188124,Total amount funded in policy code 2: 82622275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
def add_loans(csv, loans=loans):
    temp = pd.read_csv(csv, header=1)
    print "New length: " + str(len(temp)) + ", loans length: " + str(len(loans))
    if np.all(temp.columns == loans.columns):
        newloans = pd.concat([loans, temp], axis=0)
    print "New loans length: " + str(len(newloans))
    return newloans

In [56]:
newloans = add_loans("data/LoanStats3c.csv")
newloans

New length: 235631, loans length: 230663
New loans length: 466294

/Users/xeinos/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:3006: DtypeWarning: Columns (0,19) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
5,1075269,1311441.0,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6,1069639,1304742.0,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
7,1072053,1288686.0,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
8,1071795,1306957.0,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
9,1071570,1306721.0,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
10,1070078,1305201.0,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
11,1069908,1305008.0,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12,1064687,1298717.0,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13,1069866,1304956.0,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14,1069057,1303503.0,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,1069759,1304871.0,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,1065775,1299699.0,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
17,1069971,1304884.0,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
18,1062474,1294539.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19,1069742,1304855.0,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
20,1069740,1284848.0,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
21,1039153,1269083.0,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
22,1069710,1304821.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
23,1069700,1304810.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,1069559,1304634.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
25,1069697,1273773.0,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
26,1069800,1304679.0,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
27,1069657,1304764.0,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
28,1069799,1304678.0,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
29,1047704,1278806.0,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235601,9845880,11697888.0,12800.0,12800.0,12800.000000,36 months,13.53%,434.56,B,B5,...,0.0,3.0,100.0,60.0,0.0,0.0,333128.0,21372.0,37000.0,1325.0
235602,9284670,11116818.0,7000.0,7000.0,7000.000000,36 months,9.67%,224.79,B,B1,...,0.0,3.0,83.3,0.0,0.0,0.0,22933.0,18249.0,4900.0,17933.0
235603,8646060,10418080.0,18000.0,18000.0,17975.000000,36 months,15.61%,629.37,C,C4,...,0.0,2.0,94.4,75.0,1.0,0.0,76910.0,27322.0,8900.0,32710.0
235604,9795940,11647977.0,24000.0,24000.0,24000.000000,36 months,21.48%,910.13,E,E2,...,0.0,4.0,100.0,71.4,0.0,0.0,90838.0,43547.0,26100.0,57338.0
235605,9824767,11676888.0,14400.0,14400.0,14375.000000,36 months,13.53%,488.88,B,B5,...,0.0,1.0,100.0,100.0,0.0,0.0,133059.0,116175.0,17800.0,94959.0
235606,9825193,11677266.0,14000.0,14000.0,14000.000000,36 months,16.24%,493.86,C,C5,...,1.0,7.0,91.5,50.0,0.0,0.0,228197.0,44014.0,17100.0,49157.0
235607,9795013,11647121.0,15250.0,15250.0,15250.000000,36 months,17.57%,548.05,D,D2,...,0.0,1.0,90.5,42.9,1.0,1.0,60865.0,13021.0,40200.0,20665.0
235608,9765006,11617106.0,24000.0,24000.0,24000.000000,36 months,13.98%,820.04,C,C1,...,0.0,3.0,92.6,16.7,0.0,0.0,53526.0,14674.0,14800.0,33126.0
235609,9774870,11626983.0,32000.0,32000.0,31975.000000,36 months,7.90%,1001.29,A,A4,...,0.0,3.0,100.0,0.0,0.0,0.0,369066.0,16003.0,21200.0,14179.0
235610,9794642,2217122.0,12000.0,12000.0,12000.000000,36 months,8.90%,381.04,A,A5,...,0.0,1.0,95.8,50.0,0.0,0.0,31900.0,15960.0,27900.0,0.0
235611,9198304,11060277.0,10000.0,10000.0,10000.000000,36 months,12.85%,336.22,B,B4,...,1.0,0.0,81.5,33.3,0.0,0.0,57782.0,24373.0,10800.0,32682.0
235612,9656595,11508352.0,12000.0,12000.0,12000.000000,36 months,16.24%,423.31,C,C5,...,2.0,1.0,78.3,66.7,0.0,0.0,165425.0,76322.0,27700.0,66120.0
235613,9646669,11498434.0,5000.0,5000.0,5000.000000,36 months,22.40%,191.99,E,E3,...,0.0,2.0,100.0,100.0,0.0,0.0,79095.0,61201.0,10200.0,46395.0
235614,9505043,11337194.0,13250.0,13250.0,13225.000000,60 months,22.90%,372.77,E,E4,...,2.0,5.0,86.4,33.3,0.0,0.0,21300.0,10192.0,3800.0,10000.0
235615,9685861,11537845.0,10000.0,10000.0,10000.000000,36 months,7.90%,312.91,A,A4,...,0.0,3.0,97.1,40.0,0.0,0.0,186108.0,46422.0,17000.0,39708.0
235616,9686192,11538048.0,12000.0,12000.0,12000.000000,60 months,21.48%,327.89,E,E2,...,0.0,6.0,92.5,80.0,0.0,0.0,351209.0,126045.0,24800.0,107010.0
235617,9199716,11061625.0,6000.0,6000.0,6000.000000,36 months,10.99%,196.41,B,B2,...,0.0,3.0,100.0,50.0,1.0,0.0,148594.0,4946.0,7900.0,0.0
235618,9666300,9890240.0,10000.0,10000.0,10000.000000,36 months,11.99%,332.10,B,B3,...,1.0,2.0,87.5,66.7,0.0,0.0,17100.0,9557.0,11800.0,0.0
235619,9715141,11567259.0,6000.0,6000.0,6000.000000,36 months,15.61%,209.79,C,C4,...,0.0,2.0,100.0,0.0,1.0,0.0,265818.0,259863.0,4700.0,255318.0
235620,9695736,11547808.0,8525.0,8525.0,8525.000000,60 months,18.25%,217.65,D,D3,...,2.0,0.0,84.6,0.0,0.0,0.0,183122.0,13798.0,33800.0,14322.0
235621,9007579,10799568.0,18000.0,18000.0,17975.000000,36 months,7.90%,563.23,A,A4,...,1.0,3.0,90.9,0.0,0.0,0.0,97389.0,42592.0,42700.0,47089.0
235622,9745590,11597671.0,10000.0,10000.0,10000.000000,36 months,18.25%,362.78,D,D3,...,0.0,2.0,79.2,33.3,0.0,0.0,18074.0,10170.0,5600.0,6974.0
235623,9745484,11597572.0,15000.0,15000.0,15000.000000,36 months,13.53%,509.25,B,B5,...,0.0,1.0,100.0,100.0,0.0,0.0,22485.0,20140.0,16400.0,4885.0
235624,8598660,1440975.0,18400.0,18400.0,18400.000000,60 months,14.47%,432.64,C,C2,...,0.0,1.0,100.0,80.0,0.0,0.0,311049.0,184117.0,21200.0,159744.0
235625,9684700,11536848.0,22000.0,22000.0,22000.000000,60 months,19.97%,582.50,D,D5,...,0.0,2.0,100.0,20.0,1.0,0.0,263367.0,47136.0,12200.0,39347.0
235626,9584776,11436914.0,20700.0,20700.0,20700.000000,60 months,16.99%,514.34,D,D1,...,0.0,0.0,97.6,100.0,0.0,0.0,96582.0,73598.0,8500.0,83482.0
235627,9604874,11457002.0,2000.0,2000.0,2000.000000,36 months,7.90%,62.59,A,A4,...,0.0,4.0,85.2,11.1,0.0,0.0,640841.0,50896.0,47500.0,37200.0
235628,9199665,11061576.0,10000.0,10000.0,9975.000000,36 months,19.20%,367.58,D,D3,...,0.0,2.0,90.9,50.0,0.0,0.0,81470.0,57477.0,13500.0,65470.0
235629,Total amount funded in policy code 1: 3503840175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235630,Total amount funded in policy code 2: 873652739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
newloans = add_loans("data/LoanStats3d.csv", newloans)
newloans

New length: 421097, loans length: 466294
New loans length: 887391

/Users/xeinos/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:3006: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
5,1075269,1311441.0,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6,1069639,1304742.0,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
7,1072053,1288686.0,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
8,1071795,1306957.0,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
9,1071570,1306721.0,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
10,1070078,1305201.0,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
11,1069908,1305008.0,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12,1064687,1298717.0,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13,1069866,1304956.0,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14,1069057,1303503.0,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,1069759,1304871.0,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,1065775,1299699.0,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
17,1069971,1304884.0,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
18,1062474,1294539.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19,1069742,1304855.0,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
20,1069740,1284848.0,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
21,1039153,1269083.0,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
22,1069710,1304821.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
23,1069700,1304810.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,1069559,1304634.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
25,1069697,1273773.0,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
26,1069800,1304679.0,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
27,1069657,1304764.0,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
28,1069799,1304678.0,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
29,1047704,1278806.0,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421067,36500819,39232937.0,10300.0,10300.0,10300.000000,60 months,13.66%,237.86,C,C3,...,0.0,2.0,95.8,42.9,0.0,0.0,58710.0,41956.0,17100.0,36710.0
421068,36743377,39486112.0,4200.0,4200.0,4200.000000,36 months,15.99%,147.64,D,D2,...,0.0,6.0,88.9,100.0,0.0,0.0,224211.0,45512.0,5600.0,40401.0
421069,35773415,38468842.0,18700.0,18700.0,18700.000000,60 months,17.86%,473.44,D,D5,...,0.0,3.0,88.9,50.0,0.0,0.0,42499.0,40164.0,10000.0,32299.0
421070,36250801,38962184.0,6000.0,6000.0,6000.000000,36 months,17.86%,216.50,D,D5,...,0.0,2.0,100.0,100.0,0.0,0.0,412963.0,14906.0,1900.0,8085.0
421071,36371802,39103231.0,15000.0,15000.0,15000.000000,60 months,11.44%,329.44,B,B4,...,0.0,2.0,100.0,40.0,0.0,0.0,47674.0,33529.0,22500.0,21574.0
421072,36331554,39042967.0,26950.0,26950.0,26950.000000,36 months,8.19%,846.88,A,A5,...,0.0,0.0,100.0,0.0,0.0,0.0,137433.0,41650.0,124600.0,8333.0
421073,36460697,39182359.0,23000.0,23000.0,23000.000000,60 months,15.59%,554.32,D,D1,...,0.0,2.0,100.0,37.5,0.0,0.0,79510.0,48978.0,60800.0,13910.0
421074,36440728,39152101.0,25000.0,25000.0,25000.000000,60 months,15.99%,607.82,D,D2,...,0.0,0.0,100.0,100.0,0.0,0.0,18700.0,17275.0,17500.0,0.0
421075,35591131,38288343.0,25000.0,25000.0,25000.000000,60 months,15.59%,602.52,D,D1,...,0.0,1.0,100.0,37.5,0.0,0.0,24400.0,13860.0,20900.0,0.0
421076,36361815,39093260.0,26500.0,26500.0,26500.000000,60 months,8.67%,545.87,B,B1,...,0.0,0.0,95.2,50.0,0.0,0.0,214551.0,91768.0,67600.0,33501.0
421077,36201871,38913321.0,21000.0,21000.0,21000.000000,36 months,6.03%,639.15,A,A1,...,0.0,0.0,100.0,0.0,0.0,0.0,301457.0,36303.0,76300.0,36656.0
421078,36381756,39013193.0,8000.0,8000.0,8000.000000,36 months,8.19%,251.40,A,A5,...,0.0,2.0,85.2,33.3,0.0,0.0,230732.0,38259.0,5800.0,39940.0
421079,36231724,38943173.0,12000.0,12000.0,12000.000000,36 months,9.49%,384.34,B,B2,...,1.0,1.0,80.0,40.0,0.0,0.0,28183.0,20671.0,10500.0,16283.0
421080,36231718,38943165.0,10775.0,10775.0,10775.000000,36 months,6.03%,327.95,A,A1,...,0.0,0.0,90.5,0.0,0.0,0.0,60948.0,24696.0,38700.0,19248.0
421081,36381704,39013139.0,7000.0,7000.0,7000.000000,36 months,14.31%,240.30,C,C4,...,1.0,3.0,80.0,16.7,0.0,2.0,43768.0,32135.0,6900.0,33868.0
421082,36241316,38952731.0,6225.0,6225.0,6225.000000,36 months,16.49%,220.37,D,D3,...,0.0,0.0,100.0,100.0,0.0,0.0,14307.0,8357.0,1800.0,12507.0
421083,36301729,39023153.0,10000.0,10000.0,10000.000000,36 months,6.49%,306.45,A,A2,...,0.0,0.0,96.9,0.0,0.0,0.0,148298.0,88120.0,30300.0,117998.0
421084,36250208,38961532.0,13150.0,13150.0,13150.000000,60 months,14.99%,312.77,C,C5,...,0.0,0.0,100.0,0.0,0.0,0.0,190700.0,672.0,20700.0,0.0
421085,36421485,39142898.0,4000.0,4000.0,4000.000000,36 months,8.67%,126.59,B,B1,...,0.0,2.0,100.0,0.0,1.0,0.0,58334.0,18979.0,12900.0,28234.0
421086,36260758,38972123.0,10850.0,10850.0,10850.000000,36 months,19.24%,399.04,E,E2,...,0.0,3.0,90.0,50.0,0.0,0.0,81797.0,28301.0,2500.0,27533.0
421087,35094480,37777829.0,7500.0,7500.0,7500.000000,36 months,9.49%,240.22,B,B2,...,0.0,4.0,96.6,20.0,1.0,0.0,36320.0,18611.0,10700.0,21820.0
421088,36221446,38932858.0,11575.0,11575.0,11575.000000,36 months,15.59%,404.61,D,D1,...,0.0,1.0,100.0,42.9,0.0,0.0,29866.0,19798.0,27500.0,1766.0
421089,36330911,39042282.0,12000.0,12000.0,12000.000000,36 months,11.99%,398.52,B,B5,...,1.0,3.0,98.3,50.0,0.0,0.0,325484.0,112990.0,15400.0,98125.0
421090,36371250,39102635.0,10000.0,10000.0,10000.000000,36 months,11.99%,332.10,B,B5,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421091,36441262,39152692.0,24000.0,24000.0,24000.000000,36 months,11.99%,797.03,B,B5,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421092,36271333,38982739.0,13000.0,13000.0,13000.000000,60 months,15.99%,316.07,D,D2,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806,39222577.0,12000.0,12000.0,12000.000000,60 months,19.99%,317.86,E,E3,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262,38982659.0,20000.0,20000.0,20000.000000,36 months,11.99%,664.20,B,B5,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,Total amount funded in policy code 1: 6417608175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,Total amount funded in policy code 2: 1944088810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
newloans = add_loans("data/LoanStats_2016Q1.csv", newloans)
newloans

New length: 133889, loans length: 887391
New loans length: 1021280

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
5,1075269,1311441.0,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6,1069639,1304742.0,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
7,1072053,1288686.0,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
8,1071795,1306957.0,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
9,1071570,1306721.0,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
10,1070078,1305201.0,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
11,1069908,1305008.0,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12,1064687,1298717.0,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13,1069866,1304956.0,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14,1069057,1303503.0,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,1069759,1304871.0,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,1065775,1299699.0,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
17,1069971,1304884.0,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
18,1062474,1294539.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19,1069742,1304855.0,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
20,1069740,1284848.0,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
21,1039153,1269083.0,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
22,1069710,1304821.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
23,1069700,1304810.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,1069559,1304634.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
25,1069697,1273773.0,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
26,1069800,1304679.0,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
27,1069657,1304764.0,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
28,1069799,1304678.0,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
29,1047704,1278806.0,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133859,66545300,71271109.0,15000.0,15000.0,15000.000000,36 months,6.89%,462.41,A,A3,...,0.0,0.0,96.3,50.0,0.0,0.0,53500.0,38726.0,23700.0,25000.0
133860,66634609,71360435.0,11000.0,11000.0,11000.000000,36 months,9.17%,350.67,B,B2,...,0.0,2.0,84.2,66.7,0.0,0.0,220170.0,11205.0,6700.0,4000.0
133861,66444535,71170354.0,10000.0,10000.0,10000.000000,36 months,11.22%,328.43,B,B5,...,0.0,1.0,84.0,66.7,0.0,0.0,18800.0,8993.0,9600.0,0.0
133862,66563812,71289635.0,6000.0,6000.0,6000.000000,36 months,11.99%,199.26,C,C1,...,0.0,0.0,100.0,33.3,0.0,0.0,23090.0,18739.0,8600.0,12190.0
133863,66643445,71369219.0,4500.0,4500.0,4500.000000,36 months,9.76%,144.70,B,B3,...,0.0,3.0,92.9,66.7,0.0,0.0,72024.0,45799.0,15300.0,54824.0
133864,66523229,71249012.0,16800.0,16800.0,16800.000000,36 months,7.26%,520.74,A,A4,...,0.0,1.0,100.0,0.0,0.0,0.0,89659.0,60266.0,22800.0,66859.0
133865,66623289,71349080.0,7500.0,7500.0,7500.000000,36 months,9.76%,241.16,B,B3,...,0.0,4.0,92.9,0.0,0.0,0.0,24100.0,6244.0,13900.0,3500.0
133866,66453994,71179782.0,34000.0,34000.0,34000.000000,36 months,9.76%,1093.26,B,B3,...,0.0,3.0,95.2,75.0,0.0,0.0,492716.0,152127.0,49400.0,151876.0
133867,66541817,71267577.0,8500.0,8500.0,8500.000000,36 months,13.18%,287.14,C,C3,...,0.0,5.0,96.9,0.0,6.0,0.0,126731.0,113965.0,11100.0,111631.0
133868,66532821,71258601.0,12600.0,12600.0,12600.000000,60 months,18.99%,326.79,E,E3,...,0.0,2.0,92.3,0.0,0.0,0.0,49133.0,34545.0,9200.0,36133.0
133869,65792205,70424932.0,35000.0,35000.0,35000.000000,60 months,18.99%,907.73,E,E3,...,0.0,11.0,100.0,0.0,0.0,0.0,382768.0,77197.0,95600.0,64328.0
133870,66442993,71168779.0,25000.0,25000.0,24800.000000,36 months,18.99%,916.28,E,E3,...,0.0,5.0,100.0,20.0,0.0,0.0,50329.0,36743.0,10100.0,36607.0
133871,66602737,71328545.0,12000.0,12000.0,12000.000000,36 months,9.76%,385.86,B,B3,...,0.0,6.0,86.0,33.3,0.0,0.0,285157.0,16887.0,20300.0,4565.0
133872,66453496,71179264.0,5000.0,5000.0,5000.000000,36 months,13.18%,168.91,C,C3,...,0.0,2.0,94.4,0.0,0.0,0.0,51304.0,48672.0,3600.0,47704.0
133873,66492137,71217896.0,5000.0,5000.0,5000.000000,36 months,15.41%,174.34,D,D1,...,0.0,3.0,72.4,0.0,0.0,0.0,56409.0,47608.0,1000.0,46209.0
133874,66450446,71176161.0,12950.0,12950.0,12950.000000,36 months,15.41%,451.53,D,D1,...,0.0,1.0,100.0,66.7,0.0,0.0,44656.0,25960.0,14600.0,17956.0
133875,66422233,71157987.0,24000.0,24000.0,24000.000000,36 months,5.32%,722.76,A,A1,...,0.0,0.0,100.0,0.0,0.0,0.0,305629.0,14811.0,53400.0,42455.0
133876,65374128,69960908.0,21175.0,21175.0,20925.000000,60 months,19.99%,560.90,E,E4,...,0.0,1.0,100.0,100.0,0.0,0.0,84264.0,54241.0,12500.0,62764.0
133877,65855145,70549857.0,6000.0,6000.0,6000.000000,36 months,26.77%,244.22,G,G1,...,0.0,3.0,96.3,NaN,0.0,0.0,121029.0,129982.0,0.0,118629.0
133878,66501924,71227682.0,6000.0,6000.0,6000.000000,36 months,13.67%,204.11,C,C4,...,0.0,1.0,62.5,33.3,0.0,0.0,18300.0,5989.0,13300.0,0.0
133879,66421505,71157243.0,24100.0,24100.0,24100.000000,60 months,18.49%,618.43,E,E2,...,0.0,0.0,87.5,100.0,0.0,0.0,45218.0,32127.0,9300.0,31818.0
133880,66601274,71327029.0,4000.0,4000.0,4000.000000,36 months,9.17%,127.52,B,B2,...,0.0,1.0,100.0,25.0,0.0,0.0,287561.0,36850.0,25000.0,29054.0
133881,66390905,71115633.0,5000.0,5000.0,5000.000000,36 months,9.17%,159.40,B,B2,...,0.0,2.0,91.7,100.0,0.0,0.0,56555.0,28117.0,8100.0,44855.0
133882,66055600,70750350.0,6000.0,6000.0,6000.000000,36 months,9.17%,191.28,B,B2,...,0.0,3.0,100.0,66.7,1.0,0.0,45927.0,30895.0,11100.0,27327.0
133883,65854936,70549648.0,6000.0,6000.0,6000.000000,36 months,7.89%,187.72,A,A5,...,0.0,1.0,100.0,33.3,0.0,0.0,25300.0,9223.0,11600.0,3900.0
133884,66141895,70853611.0,14400.0,14400.0,14400.000000,60 months,13.18%,328.98,C,C3,...,0.0,2.0,79.0,100.0,0.0,0.0,49049.0,35979.0,5800.0,30749.0
133885,65673209,70305961.0,34050.0,34050.0,34050.000000,36 months,15.41%,1187.21,D,D1,...,0.0,1.0,95.2,50.0,0.0,0.0,152900.0,25473.0,16900.0,0.0
133886,65744272,70377038.0,5000.0,5000.0,5000.000000,36 months,11.22%,164.22,B,B5,...,0.0,1.0,100.0,75.0,1.0,0.0,223105.0,5763.0,11000.0,0.0
133887,Total amount funded in policy code 1: 2087217200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133888,Total amount funded in policy code 2: 662815446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
len(newloans)

1021280

In [66]:
newloans.iloc[969472]

id                                                                         71026905
member_id                                                               7.61188e+07
loan_amnt                                                                     15000
funded_amnt                                                                   15000
funded_amnt_inv                                                               15000
term                                                                      60 months
int_rate                                                                     12.99%
installment                                                                  341.22
grade                                                                             C
sub_grade                                                                        C2
emp_title                                                   Assistant Store Manager
emp_length                                                                  8 years
home_ownership                                                             MORTGAGE
annual_inc                                                                    54000
verification_status                                                 Source Verified
issue_d                                                                    Feb-2016
loan_status                                                                 Current
pymnt_plan                                                                        n
url                               https://lendingclub.com/browse/loanDetail.acti...
desc                                                                            NaN
purpose                                                                 credit_card
title                                                       Credit card refinancing
zip_code                                                                      660xx
addr_state                                                                       KS
dti                                                                           21.33
delinq_2yrs                                                                       1
earliest_cr_line                                                           Sep-1998
inq_last_6mths                                                                    0
mths_since_last_delinq                                                            7
mths_since_last_record                                                          NaN
                                                        ...
mo_sin_old_rev_tl_op                                                             68
mo_sin_rcnt_rev_tl_op                                                            24
mo_sin_rcnt_tl                                                                   17
mort_acc                                                                          1
mths_since_recent_bc                                                             24
mths_since_recent_bc_dlq                                                          7
mths_since_recent_inq                                                             0
mths_since_recent_revol_delinq                                                    7
num_accts_ever_120_pd                                                             0
num_actv_bc_tl                                                                    2
num_actv_rev_tl                                                                   3
num_bc_sats                                                                       2
num_bc_tl                                                                         2
num_il_tl                                                                        13
num_op_rev_tl                                                                     3
num_rev_accts                                                                     3
num_rev_tl_bal_gt_0                                                               3
num_sats                                                                          7
num_tl_120dpd_2m                                                                  0
num_tl_30dpd                                                                      0
num_tl_90g_dpd_24m                                                                0
num_tl_op_past_12m                                                                0
pct_tl_nvr_dlq                                                                 88.2
percent_bc_gt_75                                                                100
pub_rec_bankruptcies                                                              0
tax_liens                                                                         0
tot_hi_cred_lim                                                              218398
total_bal_ex_mort                                                             62847
total_bc_limit                                                                12300
total_il_high_credit_limit                                                    59698
Name: 82081, dtype: object

In [68]:
rejects = add_loans("data/RejectStatsB.csv", rdf)
rejects

New length: 2692501, loans length: 755441
New loans length: 3447942

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0
5,15000.0,2007-05-27,Trinfiniti,645.0,0%,105xx,NY,3 years,0
6,10000.0,2007-05-27,NOTIFYi Inc,693.0,10%,210xx,MD,< 1 year,0
7,3900.0,2007-05-27,For Justin.,700.0,10%,469xx,IN,2 years,0
8,3000.0,2007-05-28,title?,694.0,10%,808xx,CO,4 years,0
9,2500.0,2007-05-28,timgerst,573.0,11.76%,407xx,KY,4 years,0
10,3900.0,2007-05-28,need to consolidate,710.0,10%,705xx,LA,10+ years,0
11,1000.0,2007-05-28,sixstrings,680.0,10%,424xx,KY,1 year,0
12,3000.0,2007-05-28,bmoore5110,688.0,10%,190xx,PA,< 1 year,0
13,1500.0,2007-05-28,MHarkins,704.0,10%,189xx,PA,3 years,0
14,1000.0,2007-05-28,Moving,694.0,10%,354xx,AL,< 1 year,0
15,8000.0,2007-05-28,Recent College Grad Wants to Pay Off CCs,708.0,10%,374xx,TN,< 1 year,0
16,12000.0,2007-05-29,FoundersCafe.com,685.0,10%,770xx,TX,3 years,0
17,1000.0,2007-05-29,UChicago2004,698.0,10%,207xx,MD,3 years,0
18,15000.0,2007-05-29,Cancer is Killing My Credit,680.0,10%,432xx,OH,< 1 year,0
19,5000.0,2007-05-29,2006-2007 College Debt Loan,680.0,10%,011xx,MA,< 1 year,0
20,15000.0,2007-05-29,twbmc,712.0,10%,773xx,TX,< 1 year,0
21,5000.0,2007-05-29,Bills & Vacation,704.0,10%,212xx,MD,1 year,0
22,4950.0,2007-05-29,Vehicle Purchase/Used Auto,693.0,10%,220xx,VA,2 years,0
23,6100.0,2007-05-29,thejanman,684.0,24.69%,453xx,OH,2 years,0
24,12000.0,2007-05-29,Finish Off College,704.0,10%,462xx,IN,2 years,0
25,25000.0,2007-05-29,Phuocpnn,686.0,10%,631xx,MO,< 1 year,0
26,15000.0,2007-05-29,Established borrower consolodating debt,698.0,15.56%,559xx,MN,< 1 year,0
27,5000.0,2007-05-29,mainmanandy,719.0,10%,457xx,OH,< 1 year,0
28,10000.0,2007-05-30,Jaguar10301,602.0,2.25%,221xx,VA,< 1 year,0
29,10000.0,2007-05-30,rpinho78,475.0,21.77%,061xx,CT,< 1 year,0
...,...,...,...,...,...,...,...,...,...
2692471,4500.0,2014-12-31,car,550.0,18.42%,843xx,UT,< 1 year,0
2692472,5000.0,2014-12-31,small_business,663.0,1.59%,210xx,MD,< 1 year,0
2692473,11500.0,2014-12-31,debt_consolidation,591.0,66.13%,754xx,TX,< 1 year,0
2692474,5000.0,2014-12-31,house,501.0,555.97%,937xx,CA,< 1 year,0
2692475,10000.0,2014-12-31,credit_card,605.0,15.57%,954xx,CA,5 years,0
2692476,3000.0,2014-12-31,debt_consolidation,580.0,23.03%,300xx,GA,< 1 year,0
2692477,4000.0,2014-12-31,other,857.0,514.28%,774xx,CA,< 1 year,0
2692478,35000.0,2014-12-31,Business,719.0,10.2%,380xx,TN,7 years,0
2692479,20000.0,2014-12-31,debt_consolidation,626.0,30.01%,270xx,NC,< 1 year,0
2692480,6000.0,2014-12-31,car,563.0,4.24%,435xx,OH,< 1 year,0
2692481,25000.0,2014-12-31,debt_consolidation,NaN,-1%,995xx,AK,< 1 year,0
2692482,10000.0,2014-12-31,other,NaN,0%,560xx,MN,< 1 year,0
2692483,12600.0,2014-12-31,debt_consolidation,701.0,353.75%,785xx,TX,< 1 year,0
2692484,5000.0,2014-12-31,debt_consolidation,501.0,7.91%,606xx,IL,< 1 year,0
2692485,4000.0,2014-12-31,other,831.0,1025.3%,774xx,CA,< 1 year,0
2692486,4000.0,2014-12-31,other,754.0,120.48%,774xx,CA,< 1 year,0
2692487,25000.0,2014-12-31,other,682.0,38.62%,721xx,AR,< 1 year,0
2692488,3000.0,2014-12-31,debt_consolidation,597.0,19.4%,853xx,AZ,< 1 year,0
2692489,4000.0,2014-12-31,other,867.0,1603.53%,774xx,CA,< 1 year,0
2692490,5000.0,2014-12-31,other,656.0,4.39%,606xx,IL,< 1 year,0
2692491,7000.0,2014-12-31,credit_card,659.0,41.68%,346xx,FL,< 1 year,0
2692492,5500.0,2014-12-31,home_improvement,602.0,1.1%,293xx,SC,< 1 year,0
2692493,4000.0,2014-12-31,credit_card,634.0,2.76%,130xx,NY,< 1 year,0
2692494,16000.0,2014-12-31,car,625.0,1%,181xx,PA,< 1 year,0
2692495,10000.0,2014-12-31,debt_consolidation,646.0,23.4%,951xx,CA,< 1 year,0
2692496,20000.0,2014-12-31,Home improvement,990.0,0.13%,945xx,CA,n/a,0
2692497,5000.0,2014-12-31,debt_consolidation,509.0,0.8%,357xx,AL,< 1 year,0
2692498,300000.0,2014-12-31,Business Loan,NaN,-1%,917xx,CA,< 1 year,2
2692499,20000.0,2014-12-31,debt_consolidation,671.0,26.07%,481xx,MI,< 1 year,0
2692500,2500.0,2014-12-31,debt_consolidation,650.0,2.67%,100xx,NY,< 1 year,0

In [69]:
rejects = add_loans("data/RejectStatsC.csv", rejects)

New length: 2856149, loans length: 3447942
New loans length: 6304091

In [70]:
rejects = add_loans("data/RejectStats_2016Q1.csv", rejects)

New length: 1094190, loans length: 6304091
New loans length: 7398281

In [79]:
len(newloans[newloans['last_credit_pull_d'].isnull()])

66

In [ ]:
copydf = newloans
copydf.apply(lambda x: sum(x.isnull()),axis=0)